# Generated by Django 5.2 on 2025-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('element_selector', models.CharField(help_text='CSS selector for the element to highlight', max_length=255)),
                ('position', models.CharField(choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left')], default='bottom', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('guide_type', models.CharField(choices=[('new_user', 'New User Onboarding'), ('community_creation', 'Community Creation'), ('post_creation', 'Post Creation'), ('commenting', 'Commenting')], default='new_user', max_length=50)),
            ],
            options={
                'ordering': ['guide_type', 'order'],
            },
        ),
    ]
