# Generated by Django 5.2 on 2025-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguidestep',
            name='element_selector',
            field=models.CharField(help_text='CSS selector for the element to highlight', max_length=200),
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='guide_type',
            field=models.CharField(choices=[('new_user', 'New User Guide'), ('community_creation', 'Community Creation Guide'), ('post_creation', 'Post Creation Guide'), ('commenting', 'Commenting Guide')], default='new_user', max_length=50),
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='bottom', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userguidestep',
            unique_together={('guide_type', 'order')},
        ),
    ]
